---
- name: Install docker and docker-compose
  hosts: docker_server
  become: yes
  tasks:
    - name: Install docker
      dnf:
        name: docker
        update_cache: yes
        state: present
    - name: Start docker daemon
      systemd:
        name: docker
        state: started
        enabled: yes
    # - name: Find architecture
    #   command: uname -m
    #   register: arch
    - name: Create docker cli-plugins directory
      file:
        path: /usr/local/lib/docker/cli-plugins
        state: directory
        mode: +x
    - name: Install docker-compose
      get_url:
        # url: https://github.com/docker/compose/releases/download/v5.0.2/docker-compose-linux-{{ arch.stdout }}
        url: https://github.com/docker/compose/releases/download/v5.0.2/docker-compose-linux-x86_64
        dest: /usr/local/lib/docker/cli-plugins/docker-compose
        mode: +x

- name: Add ec2-user to docker group
  hosts: docker_server
  become: yes
  tasks:
    - name: Add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes
    - name: Reconnect to server
      meta: reset_connection

# - name: Test docker pull
#   hosts: docker_server
#   tasks: 
#     - name: Pull redis
#       community.docker.docker_image: 
#         name: redis
#         source: pull
      
- name: Start docker containers
  hosts: docker_server
  vars_files:
    - project-vars
  tasks:
    - name: Copy docker compose
      copy:
        src: /Users/mahtazare/Documents/docker-compose.yaml
        dest: /home/ec2-user/docker-compose.yaml
    - name: Docker login
      community.docker.docker_login:
        username: mahtazare
        password: "{{docker_password}}"
    - name: Start containers with docker compose
      community.docker.docker_compose_v2:
        project_src: /home/ec2-user



  